//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myriadbits.MXFInspect.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Myriadbits.MXFInspect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon ChildIcon {
            get {
                object obj = ResourceManager.GetObject("ChildIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CollapseAll {
            get {
                object obj = ResourceManager.GetObject("CollapseAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- *****DO NOT EDIT THIS XML FILE******* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- DRAFT REGISTER --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- SMPTE METADATA REGISTER --&gt;
        ///&lt;!-- ####################### --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- See https://registry.smpte-ra.org for SMPTE M [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilteredObject_13400_14x {
            get {
                object obj = ResourceManager.GetObject("FilteredObject_13400_14x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindNext_13243 {
            get {
                object obj = ResourceManager.GetObject("FindNext_13243", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindPrevious_13244 {
            get {
                object obj = ResourceManager.GetObject("FindPrevious_13244", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- *****DO NOT EDIT THIS XML FILE******* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- DRAFT REGISTER --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- SMPTE METADATA REGISTER --&gt;
        ///&lt;!-- ####################### --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- See https://registry.smpte-ra.org for SMPTE M [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HideMember_6755 {
            get {
                object obj = ResourceManager.GetObject("HideMember_6755", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- *****DO NOT EDIT THIS XML FILE******* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- DRAFT REGISTER --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- SMPTE METADATA REGISTER --&gt;
        ///&lt;!-- ####################### --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- See https://registry.smpte-ra.org for SMPTE M [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
        /// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Publi [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open_6529 {
            get {
                object obj = ResourceManager.GetObject("Open_6529", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RSReport_16xLG {
            get {
                object obj = ResourceManager.GetObject("RSReport_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap showInfo {
            get {
                object obj = ResourceManager.GetObject("showInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- *****DO NOT EDIT THIS XML FILE******* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- DRAFT REGISTER --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- SMPTE METADATA REGISTER --&gt;
        ///&lt;!-- ####################### --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- See https://registry.smpte-ra.org for SMPTE M [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
    }
}
